#!/bin/bash

set -e
set -u
set -o pipefail

TARGET="${1:-nic@singularity}"
ENV="${2:-dev}"
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SCRIPT_DIR/../..

FILENAME="dist.tar.gz"

bazel clean
bazel build //pmud:dist

ssh ${TARGET} "rm -f ${FILENAME}"
scp "bazel-bin/pmud/${FILENAME}" ${TARGET}:
ssh ${TARGET} "chmod 666 ${FILENAME}"
ssh ${TARGET} "tar xvfz ~/${FILENAME}"
ssh ${TARGET} "rm ${FILENAME}"

if [[ $TARGET =~ gcloud ]]; then
    REDIS_HOST="$(gcloud redis instances describe pmud-redis | grep host | cut -d: -f2 | tr -d ' ')"
    REDIS_PORT="$(gcloud redis instances describe pmud-redis | grep port | cut -d: -f2 | tr -d ' ')"
elif [[ $TARGET =~ sing ]]; then
    REDIS_HOST="singularity"
    REDIS_PORT=6379
fi

echo "Using:"
echo "ENV=$ENV"
echo "REDIS_HOST=$REDIS_HOST"
echo "REDIS_PORT=$REDIS_PORT"

ssh ${TARGET} "cd pmud; scripts/load-redis-static.sh $REDIS_HOST $REDIS_PORT $ENV >> ../pmud.log 2>&1 &"
ssh ${TARGET} "cd pmud; nohup scripts/run.sh $REDIS_HOST $REDIS_PORT $ENV >> ../pmud.log 2>&1 &"