#!/bin/bash

set -e
set -u
set -o pipefail

# build and run (to be invoked inside container)

export REDIS_HOST=192.168.86.25 # singularity
export REDIS_PORT=6379
export ENV=dev

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SCRIPT_DIR/../..
bazel build //pmud:pmud
cd pmud
../bazel-bin/pmud/pmud --config-file="conf/pmud.caf" conf/primordia-mud-local.yml "$@"