load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "headers",
    hdrs = ["include/graph.h", "include/BFS.h", "include/DFS.h", "include/common.h", "include/vertex.h"],
    strip_include_prefix = "include",
    include_prefix = "graph",
    visibility = ["//visibility:public"],
)