load("@rules_cc//cc:defs.bzl", "cc_binary")
load("@//:global_copts.bzl", "global_cppopts")

package(features = ["-default_compile_flags"])

cc_binary(
    name = "advent2021-01",
    srcs = ["advent2021-01.cpp"],
    copts = global_cppopts(),
)
