#!/bin/bash


gcloud compute instances add-metadata pmud \
  --project="cody-1562760462924" \
  --metadata=startup-script='#! /bin/bash
  export REDIS_HOST=10.70.181.139
  export REDIS_PORT=6379
  <<EOF'

# gcloud compute instances add-metadata pmud --metadata REDIS_HOST=10.70.181.139,REDIS_PORT=6379