#!/bin/bash

set -e
set -u
set -o pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SCRIPT_DIR/..

docker build -t vscode-cpp-container -f .devcontainer/Dockerfile .
docker run -it --rm -v $SCRIPT_DIR:/workspaces/vscode-cpp-container -w /workspaces/vscode-cpp-container vscode-cpp-container "scripts/life" "$@"