#!/bin/bash

set -e
set -u
set -o pipefail

# build and run (to be invoked inside container)

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SCRIPT_DIR/..
bazel build //pmud:pmud
cd pmud/conf
../../bazel-bin/pmud/pmud --config-file=".caf_pmud" "$@"